name: CxoTraining
services:
  cxotraining.api:
    image: ${DOCKER_REGISTRY-}cxotrainingapi
    container_name: CxoTraining
    user: root
    ports:
      - "56318:8080"
    build:
      context: .
      dockerfile: CxoTraining.Api/Dockerfile
    networks:
      - cxo_network
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
networks:
  cxo_network:
    external: true